### ISSUE TITLE
[Question] Does default depth/size behavior remain for vanilla structures?

### ISSUE THREAD

**Issue by TheGoodIdeaFairy** [Dearliet/JigsawPlus#2]
First off, holy crap this is exactly what I've been hoping for.  I've been trying to force solutions using convoluted command blocks for weeks now.  I assume this plugin will not interfere with the vanilla spawn behavior of structures and villages?

Also a brief install guide would be helpful.  Do you know if this should be compatible with Forge installs?

**Comment by Dearliet** [comment]
The plugin won't affect vanilla generation, as it only activates when the player manually triggers the jigsaw interface's generate button. Regarding mods, compatibility isn't guaranteed but is probable in most cases.
As for setting things up: Download the jar file, place it in the plugins folder, ensure ProtocolLib is installed, and then reload or restart the server. You'll gain access to the jigsaw command. Hope it helps 👍
